language: erlang
otp_release:
  - 22.0
  - 21.2.5
  - 20.3
  - 19.3
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod u+x rebar3
script:
  - ./rebar3 dialyzer
  - ./rebar3 xref
  - ./rebar3 eunit
notifications:
  email: christopher.meiklejohn@gmail.com
sudo: false
